class Settings {
  CANVAS_WIDTH = 800
  CANVAS_HEIGHT = 900 //(window.innerHeight || 600) + 10

  PLAYER_WIDTH = 50
  PLAYER_HEIGHT = 50

  ENEMY_WIDTH = 50
  ENEMY_HEIGHT = 50

  BULLET_WIDTH = 4
  BULLET_HEIGHT = 10

  SPEED_PALYER = 200
  SPEED_ENEMY = 50
  SPEED_ASTEROID = 50
  SPEED_BULLET = 300
}

export default Settings
